In [3]:
import numpy as np

In [5]:
l=[1,2,3]
l

[1, 2, 3]

In [7]:
a=np.array(l)
a

array([1, 2, 3])

In [8]:
type(l)

list

In [11]:
a.shape  #to check no of rows and column of array

(3,)

In [12]:
a.ndim #to check dimension of array

1

In [13]:
m=[[1,2,3],[3,4,5],[4,5,6]]
m

[[1, 2, 3], [3, 4, 5], [4, 5, 6]]

In [15]:
a2=np.array(m)
a2


array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [18]:

a2.ndim #euta list bhitra aarko list bhaneko 2D, list bhitra list bhitra list bhaneko 3D

2

In [19]:
a2.shape

(3, 3)

In [22]:
np.arange(0,10,2) #0 dekhi 10 samma ko value 2 ko difference ma

array([0, 2, 4, 6, 8])

In [25]:
np.random.randn(4) #standard normal distribution

array([ 0.86504612,  0.94160171,  0.12012059, -0.583261  ])

In [26]:
np.random.randn()

-1.499045085013116

In [28]:
np.random.rand(5,4) #uniform normal distribution between 0 to 1 not including 1

array([[0.68608433, 0.9042767 , 0.84100243, 0.85644956],
       [0.29243849, 0.61534929, 0.1534888 , 0.28443658],
       [0.07511837, 0.32632381, 0.00633976, 0.74152658],
       [0.52079897, 0.76326614, 0.99694129, 0.6475706 ],
       [0.70823894, 0.41919089, 0.10529521, 0.13100247]])

In [30]:
np.random.randint(1,10)

8

In [33]:
np.random.randint(1,10,5) #excluding 10, it gives five random value between 1 to 10

array([7, 6, 4, 8, 3])

In [34]:
np.random.randint(1,10,[3,3]) 

array([[5, 4, 1],
       [3, 5, 5],
       [6, 4, 4]])

In [35]:
np.random.randint(1,10,[3,3,3]) 

array([[[4, 2, 8],
        [4, 2, 4],
        [5, 4, 1]],

       [[2, 3, 6],
        [4, 4, 5],
        [2, 3, 8]],

       [[3, 7, 9],
        [6, 4, 8],
        [9, 6, 3]]])

In [36]:
np.random.randint(1,10,[2,3,3]) 

array([[[7, 3, 8],
        [5, 2, 5],
        [1, 4, 7]],

       [[3, 1, 4],
        [2, 5, 3],
        [9, 5, 4]]])

In [43]:
np.random.seed(10)  #seed ley randomness ko consistency maintain garcha, 
                            #seed value gives constant dataset for same seed value
np.random.randint(1,10,7)

array([5, 1, 2, 1, 2, 9, 1])

In [46]:
arr= np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
arr.shape

(12,)

In [48]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
s=np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
s[1]

1

In [53]:
s[-2]

8

In [54]:
s[1:9:3]

array([1, 4, 7])

In [55]:
j=np.arange(8)

In [56]:
jc=np.copy(j)  #copy whole array
jc

array([0, 1, 2, 3, 4, 5, 6, 7])

In [57]:
j[6:]=3

In [58]:
j

array([0, 1, 2, 3, 4, 5, 3, 3])

In [59]:
jc

array([0, 1, 2, 3, 4, 5, 6, 7])

In [61]:
np.random.seed(1)
abc=np.random.randint(1,10,(3,6))
abc

array([[6, 9, 6, 1, 1, 2],
       [8, 7, 3, 5, 6, 3],
       [5, 3, 5, 8, 8, 2]])

In [62]:
abc[0,0]

6

In [63]:
abc[1][2]

3

In [64]:
abc[0]

array([6, 9, 6, 1, 1, 2])

In [65]:
abc

array([[6, 9, 6, 1, 1, 2],
       [8, 7, 3, 5, 6, 3],
       [5, 3, 5, 8, 8, 2]])

In [66]:
abc[2:,2:]

array([[5, 8, 8, 2]])

In [67]:
a

array([1, 2, 3])

In [68]:
a[:-1]

array([1, 2])